import Head from "next/head";
import styles from "@/styles/Home.module.css";

import WaykeEcomWeb from "@wayke-se/ecom-web";
import "@wayke-se/ecom-web/dist/index.css";
import { useEffect, useRef } from "react";
import Link from "next/link";

export default function Home() {
  const contextRef = useRef<WaykeEcomWeb | undefined>();
  useEffect(() => {
    contextRef.current = new WaykeEcomWeb({
      id: "4a18e9a4-f7ee-458e-8bb4-9b6b8b778bbf",
      ecomSdkConfig: {
        api: {
          address: "https://ecom.wayketech.se",
        },
      },
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={() => contextRef.current?.start()}>
          Start Wayke Ecom
        </button>
        <ul>
          <li>
            <Link href="/ssr-dynamic-component">
              SSR with dynamic component
            </Link>
          </li>
          <li>
            <Link href="/ssr-dynamic-package">SSR with dynamic package</Link>
          </li>
        </ul>
      </main>
    </>
  );
}
