import Head from "next/head";
import styles from "@/styles/Home.module.css";

//import WaykeEcomWeb from "@wayke-se/ecom-web";
import "@wayke-se/ecom-web/dist/index.css";
import { Suspense, useEffect, useRef } from "react";
import { GetServerSideProps } from "next";
import dynamic from "next/dynamic";

const DynamicEcom = dynamic(() => import("../components/Ecom"), {
  loading: () => <p>Loading...</p>,
});

type SSRDynamicComponentProps = {
  product: {
    title: string;
  };
};

const SSRDynamicComponent = ({ product }: SSRDynamicComponentProps) => {
  const contextRef = useRef<any | undefined>();

  const initialize = async () => {
    const WaykeEcomWeb = (await import("@wayke-se/ecom-web")).default;
    contextRef.current = new WaykeEcomWeb({
      id: "4a18e9a4-f7ee-458e-8bb4-9b6b8b778bbf",
      ecomSdkConfig: {
        api: {
          address: "https://ecom.wayketech.se",
        },
      },
    });
  };

  useEffect(() => {
    initialize();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Dynamic load of ecom component</h1>
        <DynamicEcom />
        <div>
          <p>SSR-data</p>
          <div>Product title: {product.title}</div>
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch("https://dummyjson.com/products/1");

  const product = await response.json();

  return {
    props: {
      product,
    },
  };
};

export default SSRDynamicComponent;
